### ISSUE TITLE
댓글 입력하고 입력 값 초기화

### ISSUE THREAD

**Issue by sendkite** [thalals/MaruMaru_sparta#20]
$().val()로 입력한 값 비워보려고 했는데 안되네요.
우선 내일 다시 해보겠습니다.

**Comment by thalals** [comment]
document ()를 리로딩 하는 방식은 어떤가요?

**Comment by thalals** [comment]
아니면 자바스크립트로 document.getElementById("mTxtArea").value='';

이렇게 value값을 지울 수 있는데 적용이 될지는 잘 모르겠어요..ㅎㅎ

**Comment by sendkite** [comment]
$("#comment_content").val("")으로 해결했습니다! ""을 안넣어서 문제였어요 ㅋㅋㅋㅋㅋㅋㅋㅋ 감사합니다~~!
